{
 "title": "Juju: OVN Central (OVSDB)",
 "description": "Dashboard for OVSDB data from prometheus-ovn-exporter, running on ovn-central juju charms",
 "tags": [ "charm: ovn-central" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "query": "prometheus" },
   {
    "name": "juju_model",
    "query": {
     "query": "label_values(ovn_up,juju_model)"
    }
   },
   {
    "name": "juju_model_uuid",
    "query": {
     "query": "label_values(ovn_up{juju_model=\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "query": {
     "query": "label_values(ovn_up{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_unit",
    "query": {
     "query": "label_values(ovn_up{juju_model=\"$juju_model\", juju_model_uuid=\"$juju_model_uuid\", juju_application=\"$juju_application\"},juju_unit)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Southbound Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clustered",
   "type": "stat",
   "description": "Is OVN Southbound database clustered or standalone",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_enabled{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "stat",
   "description": "Number of nodes in the OVN Southbound cluster",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_peer_count{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Role of this unit in the OVN Southbound cluster",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_role{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Index",
   "type": "timeseries",
   "description": "Highest index of a raft log entry known to be replicated by the server\nNOTE: Real values are shown only on cluster leader",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "ovn_cluster_match_index{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Server ID - {{server_id}}"
    },
    {
     "expr": "ovn_cluster_peer_match_index{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Server ID - {{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending entries",
   "type": "timeseries",
   "description": "The number of raft entries not yet applied by the server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ovn_cluster_pending_entry_count{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  {
   "title": "Uncommited entries",
   "type": "timeseries",
   "description": "The number of raft entries not yet committed by the server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "ovn_cluster_uncommitted_entry_count{component=\"ovsdb-server-southbound\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  {
   "title": "Raft term",
   "type": "timeseries",
   "description": "Current raft term reported the server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ovn_cluster_term{component=\"ovsdb-server-southbound\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  { "title": "Northbound Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Clustered",
   "type": "stat",
   "description": "Is OVN Northbound database clustered or standalone",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_enabled{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "stat",
   "description": "Number of nodes in the OVN Northbound cluster",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_peer_count{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Role of this unit in the OVN Northbound cluster",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ovn_cluster_role{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Index",
   "type": "timeseries",
   "description": "Highest index of a raft log entry known to be replicated by the server\nNOTE: Real values are shown only on cluster leader",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 23 },
   "targets": [
    {
     "expr": "ovn_cluster_match_index{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Server ID - {{server_id}}"
    },
    {
     "expr": "ovn_cluster_peer_match_index{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "Server ID - {{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending entries",
   "type": "timeseries",
   "description": "The number of raft entries not yet applied by the server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "ovn_cluster_pending_entry_count{component=\"ovsdb-server-northbound\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  {
   "title": "Uncommited entries",
   "type": "timeseries",
   "description": "The number of raft entries not yet committed by the server",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "ovn_cluster_uncommitted_entry_count{component=\"ovsdb-server-northbound\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  {
   "title": "Raft term",
   "type": "timeseries",
   "description": "Current raft term reported the server",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ovn_cluster_term{component=\"ovsdb-server-northbound\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\".*\"}",
     "legendFormat": "{{juju_unit}} ({{server_id}})"
    }
   ]
  },
  { "title": "OVSDB Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Northbound OVSDB Event rate",
   "type": "timeseries",
   "description": "Number of events (per second) that occur in the OVSDB process",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "events/sec" } },
   "targets": [
    {
     "expr": "rate(ovn_coverage_total{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Southbound OVSDB Event rate",
   "type": "timeseries",
   "description": "Number of events (per second) that occur in the OVSDB process",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "events/sec" } },
   "targets": [
    {
     "expr": "rate(ovn_coverage_total{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Northbound OVSDB Memory Objects",
   "type": "timeseries",
   "description": "Number objects in OVSDB memory",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ovn_memory_usage{component=\"ovsdb-server-northbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{facility}}"
    }
   ]
  },
  {
   "title": "Southbound OVSDB Memory Objects",
   "type": "timeseries",
   "description": "Number objects in OVSDB memory",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ovn_memory_usage{component=\"ovsdb-server-southbound\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{facility}}"
    }
   ]
  }
 ]
}