options:
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  use-syslog:
    type: boolean
    default: False
    description: |
      Setting this to True will allow supporting services to log to syslog.
  use-internal-endpoints:
    type: boolean
    default: False
    description: |
      Openstack mostly defaults to using public endpoints for
      internal communication between services. If set to True this option
      will configure services to use internal endpoints where possible.
  ssl_cert:
    type: string
    default:
    description: |
      TLS certificate to install and use for any listening services.
      .
      __NOTE__: This configuration option will take precedence over any
                certificates received over the ``certificates`` relation.
  ssl_key:
    type: string
    default:
    description: |
      TLS key to use with certificate specified as ``ssl_cert``.
      .
      __NOTE__: This configuration option will take precedence over any
                certificates received over the ``certificates`` relation.
  ssl_ca:
    type: string
    default:
    description: |
      TLS CA to use to communicate with other components in a deployment.
      .
      __NOTE__: This configuration option will take precedence over any
                certificates received over the ``certificates`` relation.
